#config_version=6

########################
# In this file:
# - hardware declaration
# - Virtual Platform initial state
# - switches
# - coils
# - lights
########################
---

hardware:                                                                                                                                                  
  platform: opp                                                                                                                                            
  driverboards: gen2                                                                                                                                       
opp:                                                                                                                                                       
  ports: /dev/ttyACM0, /dev/ttyACM1                                                                                                                        
  chains:                                                                                                                                                  
    0: /dev/ttyACM0                                                                                                                                        
    1: /dev/ttyACM1                                                                                                                                        


###
# Virtual Platform initial state
###
virtual_platform_start_active_switches:
  - s_trough1


############
# Switches #
############
switches:
  s_left_flipper:
    number: 0-0-3
    tags: left_flipper, start
  s_bumper:
    number: 0-0-2
  s_left_flipper_eos:
    number: 0-0-1

#########
# Coils #
#########
coils:
  c_flipper_left:
    number: 0-0-3
    allow_enable: true
    default_hold_power: 0.2
    default_pulse_ms: 16
  c_flipper_left_hold:
    number: 0-0-2
    default_hold_power: 0.2
    default_pulse_ms: 16
  c_bumper:
    number: 0-0-1
    default_pulse_ms: 8

##################
#     Lights     #
##################
# lights:
#   l_triangle1:
#     number: 2-54-55-56
#   l_triangle2:
#     number: 8-9-10-11
#   l_triangle3:
#     number: 8-21-22-23
#   l_triangle4:
#     number: 9-21-22-23
#   l_triangle5:
#     number: 9-33-34-35
#   l_triangle6:
#     number: 9-54-55-56
#   l_triangle7:
#     number: 12-69-70-71
